name: chat_app
description: Bangaldeshi social media application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.6+26

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # emoji_picker: ^0.2.0
  # youtube_player_flutter: ^7.0.0+7

  uuid: ^3.0.4
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.4
  agora_rtc_engine: ^4.2.2
  #agora_rtc_engine: ^5.0.1
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.0
  image_picker: 0.8.4+4

  provider: ^6.0.2

  flutter_paginator: ^0.0.6
  photo_view: ^0.10.3
  animator: ^2.0.1
  flutter_icons: ^1.1.0
  modal_progress_hud: ^0.1.3

  #firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.7
  firebase_database: ^9.0.6

  fluttertoast: ^8.0.8
  timeago: ^3.2.2
  shared_preferences: ^2.0.5
  contacts_service: ^0.6.3
  url_launcher: ^6.0.20
  flutter_share: ^2.0.0
  device_apps: ^1.2.0

  sqflite: ^2.0.0+3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  country_code_picker: ^1.7.0

  assets_audio_player: ^3.0.4+1
  pinput: ^0.2.6
  #story_view: ^0.13.2

  vector_math: ^2.1.0
  flutter_cache_manager: ^3.3.0

  #socket_io_client: ^1.0.2
  dio: 4.0.4

  multi_image_picker: ^4.8.0
  lottie: ^1.2.2

  #flutter_rating_bar: ^4.0.0
  move_to_background: ^1.0.2
  flutter_colorpicker: ^1.0.3
  page_transition: ^2.0.5
  flutter_keyboard_visibility: ^5.2.0
  awesome_dialog: ^2.1.2
  package_info_plus: ^1.3.1

  #carousel_slider: ^4.0.0
  #shimmer: 2.0.0
  flutter_svg: ^1.0.3
  #sliding_up_panel: ^2.0.0+1
  mvc_pattern: ^8.7.0
 # video_trimmer:
 #   path: ./packages_list/video_trimmer
 # camera: ^0.9.4+12


  percent_indicator: ^4.0.0
  velocity_x: ^3.4.0
  grouped_list: ^4.2.0
  custom_pop_up_menu: ^1.2.3+1
  any_link_preview: ^2.0.6
  flutter_sound_lite: ^8.5.0
  external_path: ^1.0.1
  wakelock: ^0.6.1+2

  scrollable_positioned_list: ^0.2.3
  # Spine animation dependency
  spine_core: ^0.3.2
  spine_flutter: ^0.1.1
  fimber: ^0.6.5


  chewie: ^1.3.1
  #video_compress: ^3.1.0
  #flutter_swiper_plus: ^2.0.4


  file_picker: ^4.5.1
  video_player: ^2.2.18
  path_provider: ^2.0.9
  intl: ^0.17.0
  flutter_facebook_auth: ^3.5.4
  google_sign_in: ^5.0.3











dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.2
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audios/
    - assets/profile/
    - assets/profile/crown/
    - assets/group_profile/
    - assets/group_profile/icons/
    - assets/feed/
    - assets/big_group/
    - assets/big_group/voice_room/
    - assets/otp/
    - assets/gift/
    - assets/icon/
    - assets/icons/
    - assets/images/
    - assets/room_profile/
    - assets/anim/
    - assets/anim/girl_and_whale_polygons/
    - assets/anim/cauldron/
    - assets/anim/girl_and_whale_rectangles/
    - assets/anim/owl/
    - assets/anim/raptor/
    - assets/anim/spineboy/
    - assets/anim/spineboy-pro/
    - assets/anim/riksaw_noka/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Sans
     fonts:
       - asset: fonts/SansitaSwashed-Light.ttf
         weight: 300
   - family: Segoe
     fonts:
       - asset: fonts/segoeuil.ttf
         weight: 300
       - asset: fonts/Segoe UI Bold.ttf
         weight: 700
       - asset: fonts/segoeuil.ttf
         weight: 400
       - asset: fonts/seguisb.ttf
         weight: 600
   - family: Roboto
     fonts:
       - asset: fonts/Roboto-Black.ttf
         weight: 900
       - asset: fonts/Roboto-Light.ttf
         weight: 300
       - asset: fonts/Roboto-Thin.ttf
         weight: 100
   - family: Montserrat
     fonts:
       - asset: fonts/Montserrat-Regular.ttf
         weight: 400
   - family: Calibri
     fonts:
       - asset: fonts/Calibri-regular.ttf
         weight: 400
       - asset: fonts/calibri-bold.ttf
         weight: 600




  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
